=== codicis/gsma-sdk/gsma-core/src/main/resources/dictfiles/dictionary.dtd
<!ELEMENT Dictionary (Avp)*>
<!ELEMENT Avp (Enum|GroupAvp)*>
<!ATTLIST Avp
        Code CDATA #REQUIRED
        Vendor CDATA #REQUIRED
        Name CDATA #REQUIRED
        Type CDATA #REQUIRED
        FlagsMask (Vendor|Mandatory|VendorMandatory) "VendorMandatory"
        FlagsValues (Vendor|Mandatory|VendorMandatory|None) "None"
>
<!ELEMENT Enum (#PCDATA)>
<!ATTLIST Enum
        Name CDATA #REQUIRED
        Value CDATA #REQUIRED>
<!ELEMENT GroupAvp (#PCDATA)>
<!ATTLIST GroupAvp
        Name CDATA #REQUIRED
        Necissity CDATA #REQUIRED>

=== codicis/gsma-sdk/gsma-core/src/main/resources/dictfiles/dcca_dict.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE Dictionary SYSTEM "dictionary.dtd">

<Dictionary>
<!-- CC-Correlation-Id -->
{
    <!-- 
       OctetString. 
    -->
    <Avp Code="411" Vendor="0" Name="CC-Correlation-Id" Type="OctetString" FlagsMask="VendorMandatory" FlagsValues="Mandatory" />
    
               
<!-- CC-Input-Octets -->
{
    <!-- 
       Unsigned64. 
    -->
    <Avp Code="412" Vendor="0" Name="CC-Input-Octets" Type="Unsigned64"  FlagsMask="VendorMandatory" FlagsValues="Mandatory" /> 
    
               
<!-- CC-Output-Octets -->
{
    <!-- 
       Unsigned64. 
    -->
    <Avp Code="414" Vendor="0" Name="CC-Output-Octets" Type="Unsigned64"  FlagsMask="VendorMandatory" FlagsValues="Mandatory" />
               
<!-- CC-Request-Number -->
{
    <!-- 
       Unsigned32. 
    -->
    <Avp Code="415" Vendor="0" Name="CC-Request-Number" Type="Unsigned32" FlagsMask="VendorMandatory" FlagsValues="Mandatory"/>
}

<!-- CC-Request-Type -->
    <Avp Code="416" Vendor="0" Name="CC-Request-Type" Type="Enumerated" FlagsMask="VendorMandatory" FlagsValues="Mandatory">
        <Enum Name="INITIAL_REQUEST" Value="1" />
        <Enum Name="UPDATE_REQUEST" Value="2" />
        <Enum Name="TERMINATION_REQUEST" Value="3" />
        <Enum Name="EVENT_REQUEST" Value="4" />
    </Avp>


<!-- CC-Service-Specific-Units -->
{
    <!-- 
       Unsigned64. 
    -->
    <Avp Code="417" Vendor="0" Name="CC-Service-Specific-Units" Type="Unsigned64"  FlagsMask="VendorMandatory" FlagsValues="Mandatory" />

    <!-- CC-Session-Failover -->
{
    <!-- 
       Enumerated. 
    -->
    <Avp Code="418" Vendor="0" Name="CC-Session-Failover" Type="Enumerated" FlagsMask="VendorMandatory" FlagsValues="Mandatory" >
        <Enum Name="FAILOVER_NOT_SUPPORTED" Value="0" />
        <Enum Name="FAILOVER_SUPPORTED" Value="1" />
    </Avp> 
               
<!-- CC-Sub-Session-Id -->
{
    <!-- 
       Unsigned64. 
    -->
    struct dict_avp_data data = { 
	419,                                    <!-- Code -->
	0,                                      <!-- Vendor -->
	"CC-Sub-Session-Id",                    <!-- Name -->
	AVP_FLAG_VENDOR | AVP_FLAG_MANDATORY,   <!-- Fixed flags -->
	AVP_FLAG_MANDATORY,                     <!-- Fixed flag values -->
	AVP_TYPE_UNSIGNED64                     <!-- base type of data -->
    };
    CHECK_dict_new( DICT_AVP, data , NULL, NULL);
}

    <Avp Code="420" Vendor="0" Name="CC-Time" Type="Unsigned32"  FlagsMask="VendorMandatory" FlagsValues="Mandatory" />
                                    
<!-- CC-Total-Octets -->
{
    <!-- 
       Unsigned64. 
    -->
    <Avp Code="421" Vendor="0" Name="CC-Total-Octets" Type="Unsigned64"  FlagsMask="VendorMandatory" FlagsValues="Mandatory" />

               
<!-- CC-Unit-Type -->
{
    <!-- 
       Enumerated. 
    -->

    struct dict_object              *type;
    struct dict_type_data           tdata = { AVP_TYPE_INTEGER32, "Enumerated(CC-Unit-Type)" , NULL, NULL, NULL };
    struct dict_enumval_data        t_1 = { "TIME", { .i32 = 0 }};
    struct dict_enumval_data        t_2 = { "MONEY", { .i32 = 1 }};
    struct dict_enumval_data        t_3 = { "TOTAL-OCTETS", { .i32 = 2 }};
    struct dict_enumval_data        t_4 = { "INPUT-OCTETS", { .i32 = 3 }};
    struct dict_enumval_data        t_5 = { "OUTPUT-OCTETS", { .i32 = 4 }};
    struct dict_enumval_data        t_6 = { "SERVICE-SPECIFIC-UNITS", { .i32 = 5 }};
                 

    struct dict_avp_data    data = { 
	454,                                    <!-- Code -->
	0,                                      <!-- Vendor -->
	"CC-Unit-Type",                         <!-- Name -->
	AVP_FLAG_VENDOR | AVP_FLAG_MANDATORY,   <!-- Fixed flags -->
	AVP_FLAG_MANDATORY,                     <!-- Fixed flag values -->
	AVP_TYPE_INTEGER32                      <!-- base type of data -->
    };
    <!-- Create the Enumerated type, and then the AVP -->
    CHECK_dict_new( DICT_TYPE, tdata , NULL, type);
    CHECK_dict_new( DICT_ENUMVAL, t_1 , type, NULL);   
    CHECK_dict_new( DICT_ENUMVAL, t_2 , type, NULL); 
    CHECK_dict_new( DICT_ENUMVAL, t_3 , type, NULL); 
    CHECK_dict_new( DICT_ENUMVAL, t_4 , type, NULL); 
    CHECK_dict_new( DICT_ENUMVAL, t_5 , type, NULL); 
    CHECK_dict_new( DICT_ENUMVAL, t_6 , type, NULL); 
    CHECK_dict_new( DICT_AVP, data , type, NULL);
}

<!-- Check-Balance-Result -->
{
    <!-- 
       Enumerated. 
    -->

    struct dict_object              *type;
    struct dict_type_data           tdata = { AVP_TYPE_INTEGER32, "Enumerated(Check-Balance-Result)" , NULL, NULL, NULL };
    struct dict_enumval_data        t_1 = { "ENOUGH_CREDIT", { .i32 = 0 }};
    struct dict_enumval_data        t_2 = { "NO_CREDIT", { .i32 = 1 }};
                 

    struct dict_avp_data    data = { 
	422,                                    <!-- Code -->
	0,                                      <!-- Vendor -->
	"Check-Balance-Result",                 <!-- Name -->
	AVP_FLAG_VENDOR | AVP_FLAG_MANDATORY,   <!-- Fixed flags -->
	AVP_FLAG_MANDATORY,                     <!-- Fixed flag values -->
	AVP_TYPE_INTEGER32                      <!-- base type of data -->
    };
    <!-- Create the Enumerated type, and then the AVP -->
    CHECK_dict_new( DICT_TYPE, tdata , NULL, type);
    CHECK_dict_new( DICT_ENUMVAL, t_1 , type, NULL);  
    CHECK_dict_new( DICT_ENUMVAL, t_2 , type, NULL); 
    CHECK_dict_new( DICT_AVP, data , type, NULL);
}
               
<!-- Cost-Unit -->
{
    <!-- 
       UTF8String. 
    -->
    struct dict_avp_data    data = { 
	424,                                    <!-- Code -->
	0,                                      <!-- Vendor -->
	"Cost-Unit",                            <!-- Name -->
	AVP_FLAG_VENDOR | AVP_FLAG_MANDATORY,   <!-- Fixed flags -->
	AVP_FLAG_MANDATORY,                     <!-- Fixed flag values -->
	AVP_TYPE_OCTETSTRING                    <!-- base type of data -->
    };
    CHECK_dict_new( DICT_AVP, data , UTF8String_type, NULL);
} 
               
<!-- Credit-Control -->
{
    <!-- 
       Enumerated. 
    -->

    struct dict_object              *type;
    struct dict_type_data           tdata = { AVP_TYPE_INTEGER32, "Enumerated(Credit-Control)" , NULL, NULL, NULL };
    struct dict_enumval_data        t_1 = { "CREDIT_AUTHORIZATION", { .i32 = 0 }};
    struct dict_enumval_data        t_2 = { "RE_AUTHORIZATION", { .i32 = 1 }};
                 
    struct dict_avp_data    data = { 
	426,                                    <!-- Code -->
	0,                                      <!-- Vendor -->
	"Credit-Control",                       <!-- Name -->
	AVP_FLAG_VENDOR | AVP_FLAG_MANDATORY,   <!-- Fixed flags -->
	AVP_FLAG_MANDATORY,                     <!-- Fixed flag values -->
	AVP_TYPE_INTEGER32                      <!-- base type of data -->
    };
    <!-- Create the Enumerated type, and then the AVP -->
    CHECK_dict_new( DICT_TYPE, tdata , NULL, type);
    CHECK_dict_new( DICT_ENUMVAL, t_1, type, NULL); 
    CHECK_dict_new( DICT_ENUMVAL, t_2, type, NULL);
    CHECK_dict_new( DICT_AVP, data , type, NULL);
}
  
<!-- Credit-Control-Failure-Handling -->
{
    <!-- 
       Enumerated. 
    -->

    <Avp Code="427" Vendor="0" Name="Credit-Control-Failure-Handling" Type="Enumerated" FlagsMask="VendorMandatory" FlagsValues="Mandatory">
        <Enum Name="TERMINATE" Value="0" />
        <Enum Name="CONTINUE" Value="1" />
        <Enum Name="RETRY_AND_TERMINATE" Value="2" />
    </Avp>


<!-- Currency-Code -->
{
    <!-- 
       Unsigned32. 
    -->
    struct dict_avp_data data = { 
	425,                                    <!-- Code -->
	0,                                      <!-- Vendor -->
	"Currency-Code",                        <!-- Name -->
	AVP_FLAG_VENDOR | AVP_FLAG_MANDATORY,   <!-- Fixed flags -->
	AVP_FLAG_MANDATORY,                     <!-- Fixed flag values -->
	AVP_TYPE_UNSIGNED32                     <!-- base type of data -->
    };
    CHECK_dict_new( DICT_AVP, data , NULL, NULL);
}

<!-- Direct-Debiting-Failure-Handling -->
{
    <!-- 
       Enumerated. 
    -->

    struct dict_object              *type;
    struct dict_type_data           tdata = { AVP_TYPE_INTEGER32, "Enumerated(Direct-Debiting-Failure-Handling)" , NULL, NULL, NULL };
    struct dict_enumval_data        t_1 = { "TERMINATE_OR_BUFFER", { .i32 = 0 }};
    struct dict_enumval_data        t_2 = { "CONTINUE", { .i32 = 1 }};
                 
    struct dict_avp_data    data = { 
	428,                                    <!-- Code -->
	0,                                      <!-- Vendor -->
	"Direct-Debiting-Failure-Handling",     <!-- Name -->
	AVP_FLAG_VENDOR | AVP_FLAG_MANDATORY,   <!-- Fixed flags -->
	AVP_FLAG_MANDATORY,                     <!-- Fixed flag values -->
	AVP_TYPE_INTEGER32                      <!-- base type of data -->
    };
    <!-- Create the Enumerated type, and then the AVP -->
    CHECK_dict_new( DICT_TYPE, tdata , NULL, type);
    CHECK_dict_new( DICT_ENUMVAL, t_1 , type, NULL); 
    CHECK_dict_new( DICT_ENUMVAL, t_2 , type, NULL);
    CHECK_dict_new( DICT_AVP, data , type, NULL);
}

<!-- Exponent -->
{
    <!-- 
       Integer32. 
    -->
    struct dict_avp_data data = { 
	429,                                    <!-- Code -->
	0,                                      <!-- Vendor -->
	"Exponent",                             <!-- Name -->
	AVP_FLAG_VENDOR | AVP_FLAG_MANDATORY,   <!-- Fixed flags -->
	AVP_FLAG_MANDATORY,                     <!-- Fixed flag values -->
	AVP_TYPE_INTEGER32                      <!-- base type of data -->
    };
    CHECK_dict_new( DICT_AVP, data , NULL, NULL);
}
               
<!-- Final-Unit-Action -->
    <Avp Code="449" Vendor="0" Name="Final-Unit-Action" Type="Enumerated" FlagsMask="VendorMandatory" FlagsValues="Mandatory">
        <Enum Name="TERMINATE" Value="0" />
        <Enum Name="REDIRECT" Value="1" />
        <Enum Name="RESTRICT_ACCESS" Value="2" />
    </Avp>
{
    <!-- 
       Enumerated. 
    -->
